### ISSUE TITLE
Add a github greeting bot wob24 level 1

### ISSUE THREAD

**Issue by SendouD** [SendouD/saveXross#11]
Github Greetings bot that sends auto messages to greet new users @KiranBaliga

**Comment by KiranBaliga** [comment]
@SendouD please assign this issue to me to take this forward. Thank you. Also you can close the duplicate issue with same name or i will merge them both with one PR.

**Comment by KiranBaliga** [comment]
@SendouD Please review the PR and action accordingly. Please add wob24, level1, gssoc24-ext labels to the PR and issue.
